name: Build && Deploy Sanity
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build Sanity
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://jorgel.sanity.studio/
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Project Dependencies
        run: |
          npm ci
          npm install -g @sanity/cli
      - name: Build Sanity Backend
        run: npm run build --if-present
      - name: Verify Build
        run: ls -la dist
      - name: Deploy Sanity by @${{ github.actor }}
        run: |
          set -e
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" npx sanity deploy
#      - name: Upload artifact in order to deploy
#        uses: actions/upload-artifact@v3
#        with:
#          name: production
#          path: ./dist
#          retention-days: 5

#  deploy:
#    name: Deploy Sanity
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: production
#      url: https://jorgel.sanity.studio/
#    steps:
#      - name: Download Artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: production
#          path: ./dist
#      - name: Display structure of downloaded files
#        run: ls -la dist
#      - name: Deploy Sanity by @${{ github.actor }}
#        run: |
#          set -e
#          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" npx sanity deploy
