name: Build && Deploy Sanity
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Sanity
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Project Dependencies
        run: npm ci
      - name: Build Sanity Backend
        run: npm run build --if-present
      - name: Verify Build
        run: ls -la dist
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: ./dist
          retention-days: 5

  deploy:
    name: Deploy Sanity
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: https://iamwarning.github.io/sanity-backend/studio
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: production
          path: ./dist
      - name: Display structure of downloaded files
        run: ls -la dist
      - name: Deploy Sanity by @${{ github.actor }}
        uses: peaceiris/actions-gh-pages@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ':rocket: Deploy to gh-pages '
